import os

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_DB = os.getenv("POSTGRES_DB")
SECRET_KEY = os.getenv("SECRET_KEY")
YOS_ACCESS_KEY_ID = os.getenv("YOS_ACCESS_KEY_ID")
YOS_SECRET_ACCESS_KEY = os.getenv("YOS_SECRET_ACCESS_KEY")
YOS_ENDPOINT_URL = os.getenv("YOS_ENDPOINT_URL")
YOS_REGION_NAME = os.getenv("YOS_REGION_NAME")
YOS_POSTERS_BUCKET_NAME = os.getenv("YOS_POSTERS_BUCKET_NAME")
YOS_TRACKS_BUCKET_NAME = os.getenv("YOS_TRACKS_BUCKET_NAME")

POSTGRES_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:5432/{POSTGRES_DB}"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 60 * 24
